version: '3'

services:
  db:
    image: postgres
    container_name: "goa"
    environment:
      - POSTGRES_PASSWORD=goa
      - POSTGRES_USER=goa
      - POSTGRES_DB=goa
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    ports:
      - "4000:4000"
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
volumes:
  data:
